[package]
name = "http_zero_nine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
home = "0.5.4"
sargparse = "0.2.2"
